
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B001', 'Cien años de soledad', '1967', 'A001');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B002', 'El amor en los tiempos del cólera', '1985', 'A001');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B003', 'Harry Potter y la piedra filosofal', '1997', 'A002');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B004', '1984', '1949', 'A003');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B005', 'Orgullo y prejuicio', '1813', 'A004');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B006', 'Don Quijote de la Mancha', '1605', 'A005');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B007', 'Las aventuras de Tom Sawyer', '1876', 'A006');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B008', 'El gran Gatsby', '1925', 'A008');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B009', 'Ana Karenina', '1878', 'A009');
INSERT INTO BOOKS (ID, TITLE, YEAR, AUTHOR_ID) VALUES ('B010', 'Kafka en la orilla', '2002', 'A010');


