#quarkus.http.port=8888

health.config.ready=true
health.config.live=true

redis.host=redis://localhost:6379
redis.type=standalone
quarkus.redis.hosts=${redis.host}
quarkus.redis.client-type=${redis.type}
#quarkus.redis.password=password

#Se refiere al nombre de la cache
quarkus.cache.redis.authors.key-type=java.lang.String
quarkus.cache.redis.authors.value-type=es.upsa.ssi.common.entity.Author
quarkus.cache.redis.books.key-type=java.lang.String
quarkus.cache.redis.books.value-type=es.upsa.ssi.common.entity.Book


authors.remote=http://localhost:8081/
books.remote=http://localhost:8082/
authors.remote.api/mp-rest/uri=${authors.remote}
books.remote.api/mp-rest/uri=${books.remote}

quarkus.smallrye-openapi.enable=true
quarkus.smallrye-openapi.path=/openapi

quarkus.swagger-ui.enable=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true


quarkus.index-dependency.common.group-id=es.upsa.ssi
quarkus.index-dependency.common.artifact-id=common