local.datasource.datasource-class=org.postgresql.ds.PGSimpleDataSource

local.datasource.url=jdbc:postgresql://${database.host}:${database.port}/${database.name}

local.datasource.user=${database.username}

local.datasource.password=${database.password}


# Valeurs par défaut pour l'exécution locale
database.host=localhost
database.port=5432
database.name=upsa
database.username=system

# Le mot de passe doit être fourni via la variable
# d'environnement DATABASE_PASSWORD


#local.flyway.datasource-name=xxx,yyy,zzz

local.flyway.locations=db/migration

local.flyway.clean-at-start=false

local.flyway.migrate-at-start=true

health.config.ready=true

health.config.live=true