local.datasource.datasource-class=org.postgresql.ds.PGSimpleDataSource

local.datasource.url=jdbc:postgresql://${database.host}:${database.port}/${database.name}

local.datasource.user=${database.username}

local.datasource.password=${database.password}

database.host=localhost

database.port=5432

database.name=upsa

database.username=system

# La contraseña debe proporcionarse mediante
# la variable de entorno DATABASE_PASSWORD

#local.flyway.datasource-name=xxx,yyy,zzz

local.flyway.locations=db/migration

local.flyway.clean-at-start=false

local.flyway.migrate-at-start=true

health.config.ready=true

health.config.live=true