
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A001', 'Gabriel García Márquez', 'Colombia');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A002', 'J.K. Rowling', 'Reino Unido');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A003', 'George Orwell', 'Reino Unido');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A004', 'Jane Austen', 'Reino Unido');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A005', 'Miguel de Cervantes', 'España');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A006', 'Mark Twain', 'Estados Unidos');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A007', 'Franz Kafka', 'Austria');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A008', 'F. Scott Fitzgerald', 'Estados Unidos');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A009', 'Leo Tolstoy', 'Rusia');
INSERT INTO AUTHORS (ID, NAME, NATIONALITY) VALUES ('A010', 'Haruki Murakami', 'Japón');